### ISSUE TITLE
Extract and Run Python is broken?

### ISSUE THREAD

**Issue by tradergt** [lalten/rules_appimage#150]
When I create an appimage using bazel and execute it, it works exactly as its supposed to. However, when I run it in a container, it wont work. That, of course, is where `appimage-extract-and-run` comes in.

When I run it via appimage-extract-and-run, it can not find the python3 executable. 

`/usr/bin/env: 'python3': No such file or directory`

When I look, it seems to run AppRun which looks like: 

```#!/bin/sh
export OLDPWD
export PWD="/tmp/bazel-working-directory/_main"
export SHLVL="1"
export TMPDIR="/tmp"
[ "${BUILD_WORKING_DIRECTORY+1}" ] || export BUILD_WORKING_DIRECTORY="$OWD"
workdir="$(dirname $0)/database/mysql/bin/change_instruments.runfiles/_main"
export RUNFILES_DIR="$(dirname "${workdir}")"
cd "${workdir}"
exec "./database/mysql/bin/change_instruments" "$@"
```
The problem with the above is it's pointing to python being in #!/usr/bin/python3. There is no python installed in the container. I do see the python install buried in the /tmp/appimage_extracted*. I think the apprun above is incorrect. It should point to the buried python3, right?

**Comment by lalten** [comment]
This is due to https://github.com/bazelbuild/rules_python/issues/691 and unrelated to rules_appimage, which is entirely language agnostic (as far as the payload binary goes).

People have played around with the customizeable shebang line of the Python wrapper that Bazel generates as an entrypoint for you.
I hear that Aspect's rules_py doesn't require a bootstrap Python but I haven't used that myself yet.
(Or you could just install a host python inside your container)

**Comment by tradergt** [comment]
I have switched to using aspect_rules_py.  It fixes the above problem.
Thanks for your help as it pointed me in the right direction!
