### ISSUE TITLE
Incompatible with rules_prcross

### ISSUE THREAD

**Issue by chestnutprog** [lalten/rules_appimage#161]
Symbol links created by https://github.com/jvolkman/rules_pycross will be wrongly packed in the appimage. The problem is pycross' depsets only include a single dictionary, so https://github.com/lalten/rules_appimage/blob/87277aa09e2b33dcacc813dd0f4db71c07e97f86/appimage/private/tool/mkappimage.py#L134 will directly add whole dictionary full of symlinks into new_manifest_data.
![image](https://github.com/lalten/rules_appimage/assets/13086194/0aca2a4e-6769-47e0-800f-9330d34e797f)

**Comment by lalten** [comment]
So rules_pycross targets have just a single directory (not sure what dictionary you mean here?) as runfiles? Is that dir a TreeArtifact? or are the deps inside the dir just undeclared?

I think the current behavior of copying directory dependencies as-is is correct in rules_appimage. It's pretty ambiguous what should be done with them, and Bazel will even warn you (`input 'tests/dir' to //tests:appimage_py is a directory; dependency checking of directories is unsound`)

Can you maybe share the manifest.json rules_appimage generates for a rules_pycross target?
Maybe @jvolkman has some insights here as well?

**Comment by jvolkman** [comment]
> Maybe @jvolkman has some insights here as well?

Hello.

One of `rules_pycross`' features is building sdists into wheels in build actions, rather than in repository rules. Because of this, it also extracts Python wheels in build actions rather than repository rules, so the only thing added to the dependency graph is a single `TreeArtifact` containing the contents of the extracted wheel.

The relevant starlark is [here](https://github.com/jvolkman/rules_pycross/blob/main/pycross/private/wheel_library.bzl).

**Comment by lalten** [comment]
@chestnutprog please check if https://github.com/lalten/rules_appimage/pull/173 resolves this issue for you
